name:  ContextMenu
author:  davidwalsh
current:  1.0
category:  Interface
tags:  [menu,context,events]
docs:  http://davidwalsh.name/mootools-context-menu
demo:  http://davidwalsh.name/mootools-context-menu